name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install node and yarn dependencies
        uses: ./.github/actions/node

      - name: Install apt dependencies
        run: |
          sudo add-apt-repository universe
          sudo apt-cache show doxygen | grep Version
          sudo apt install -y doxygen=1.9.1-2ubuntu2

      - name: Build docs
        run: grunt docs

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          token: ${{ secrets.GITHUB_TOKEN }}
