name: Publish documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Install node and yarn dependencies
        uses: ./.github/actions/node

      - name: Install apt dependencies
        run: sudo apt install -y doxygen

      - name: Build docs
        run: grunt docs

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build