name: Review

on: [push, pull_request]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install

      - name: Run linters
        run: |
          npx cspell . --dot
          cppclean . --include-path $CPPPATH
          cppcheck **/*.*pp -q --enable=all --suppressions-list=.cppcheck
          scons --typecheck
        env:
          CPPPATH: /usr/include
